spring:
  application:
    name: hw5
  datasource:
    url: jdbc:h2:mem:hw5db
    driverClassName: org.h2.Driver
    username: hw5db
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
application:
  issue:
    max-allowed-books: 4