create table books (id bigint generated by default as identity, name varchar(255), primary key (id))
create table issues (id bigint generated by default as identity, id_book bigint, id_reader bigint, issued_at timestamp(6), returned_at timestamp(6), primary key (id))
create table readers (id bigint generated by default as identity, name varchar(255), primary key (id))